/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/case.glb -o app/components/Case.jsx -r public
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Case(props) {
  const { nodes, materials } = useGLTF('/models/case.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={50}>
        <group scale={0.01}>
          <mesh geometry={nodes.Object_12.geometry} material={materials.VWRclvsoDtTiCpL} position={[0, -1.307, -1.063]} rotation={[-2.007, 0, 0]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.VWRclvsoDtTiCpL_0} position={[0, -1.307, -1.063]} rotation={[-2.007, 0, 0]} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.WwrjthXqFCMqrXz} position={[0, -1.307, -1.063]} rotation={[-2.007, 0, 0]} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.WwrjthXqFCMqrXz} position={[0, -1.307, -1.063]} rotation={[-2.007, 0, 0]} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.FesGvQOXeqPgsWH} position={[0, -1.307, -1.063]} rotation={[-2.007, 0, 0]} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.VWRclvsoDtTiCpL} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.FesGvQOXeqPgsWH} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.zooxFfrwBWnUQdD} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.VWRclvsoDtTiCpL} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.IeVHhwRkexGaklQ} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.LbkTACDHYUSZcjk} />
          <mesh geometry={nodes.Object_40.geometry} material={materials.fmVudrmHBnZziCY} />
          <mesh geometry={nodes.Object_42.geometry} material={materials.oVFezdFDxINspYe} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.fmVudrmHBnZziCY} />
          <mesh geometry={nodes.Object_46.geometry} material={materials.fmVudrmHBnZziCY} />
          <mesh geometry={nodes.Object_48.geometry} material={materials.LbkTACDHYUSZcjk} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.fmVudrmHBnZziCY} />
          <mesh geometry={nodes.Object_52.geometry} material={materials.WwrjthXqFCMqrXz} />
          <mesh geometry={nodes.Object_55.geometry} material={materials.PhtTSPZPCvSsFwP} />
          <mesh geometry={nodes.Object_57.geometry} material={materials.WwrjthXqFCMqrXz} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.WwrjthXqFCMqrXz} />
          <mesh geometry={nodes.Object_61.geometry} material={materials.FesGvQOXeqPgsWH} />
          <mesh geometry={nodes.Object_63.geometry} material={materials.FesGvQOXeqPgsWH} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/case.glb')
