/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/right-airpod.glb -o app/components/Right-airpod.jsx -r public 
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from "gsap";

export function RightAirpod(props) {
  const ref = useRef()
  const { nodes, materials } = useGLTF('/models/right-airpod.glb')

  useEffect(() => {
    if (!ref.current) return

    ref.current.position.y = -0.5  // start below

    gsap.to(ref.current.position, {
      y: 0,
      duration: 1.2,
      ease: 'power3.out',
      delay: 0.3
    })
  }, [])
  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[1, 1.2, 0.7]} rotation={[1.254, 0.542, 1.864]} scale={0.5}>
        <mesh geometry={nodes.Object_112.geometry} material={materials.uxJORKAoxKXCbDN} />
        <mesh geometry={nodes.Object_114.geometry} material={materials.vdKonUzpqPTDVLw} />
        <mesh geometry={nodes.Object_117.geometry} material={materials.FesGvQOXeqPgsWH} />
        <mesh geometry={nodes.Object_119.geometry} material={materials.BExwFhrXMdSkVou} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.wlGBfgcDjjktGKi} />
        <mesh geometry={nodes.Object_124.geometry} material={materials.vdKonUzpqPTDVLw} />
        <mesh geometry={nodes.Object_126.geometry} material={materials.wlGBfgcDjjktGKi} />
        <mesh geometry={nodes.Object_128.geometry} material={materials.WwrjthXqFCMqrXz} />
        <mesh geometry={nodes.Object_132.geometry} material={materials.WwrjthXqFCMqrXz} />
        <mesh geometry={nodes.Object_134.geometry} material={materials.BCEMLtzLOrRpykF} />
        <mesh geometry={nodes.Object_137.geometry} material={materials.qUpSUfeNQBdmagr} />
        <mesh geometry={nodes.Object_139.geometry} material={materials.qUpSUfeNQBdmagr} />
        <mesh geometry={nodes.Object_141.geometry} material={materials.WwrjthXqFCMqrXz} />
        <mesh geometry={nodes.Object_144.geometry} material={materials.vdKonUzpqPTDVLw} />
        <mesh geometry={nodes.Object_146.geometry} material={materials.vdKonUzpqPTDVLw} />
        <mesh geometry={nodes.Object_149.geometry} material={materials.HsvhXbFCGvnKLqR} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/right-airpod.glb')
